### ISSUE TITLE
Removed illegal ... component. with Scripts not present in LethalSDK.

### ISSUE THREAD

**Issue by Xaymar** [HolographicWings/LethalSDK#3]
I'm making a new moon and use quite a few scripts to remove tedious work on the editing side, such as generating random foliage, ladders, and other things. All the scripts are bundled into a separate mod, which loads fine and the scripts themselves are also loaded. However when I attempt to use them in a moon, the following LethalExpansion message is printed to the log file:

```
[Warning:LethalExpansion] Removed illegal LadderGenerator component.
```

Is there a way to get this working?

**Comment by HolographicWings** [comment]
> I'm making a new moon and use quite a few scripts to remove tedious work on the editing side, such as generating random foliage, ladders, and other things. All the scripts are bundled into a separate mod, which loads fine and the scripts themselves are also loaded. However when I attempt to use them in a moon, the following LethalExpansion message is printed to the log file:
> 
> ```
> [Warning:LethalExpansion] Removed illegal LadderGenerator component.
> ```
> 
> Is there a way to get this working?

custom scrips are not allowed for safety of players

**Comment by HolographicWings** [comment]
> I'm making a new moon and use quite a few scripts to remove tedious work on the editing side, such as generating random foliage, ladders, and other things. All the scripts are bundled into a separate mod, which loads fine and the scripts themselves are also loaded. However when I attempt to use them in a moon, the following LethalExpansion message is printed to the log file:
> 
> ```
> [Warning:LethalExpansion] Removed illegal LadderGenerator component.
> ```
> 
> Is there a way to get this working?

custom scrips are not allowed for safety of players
i removed your other issue where you show how to inject new ones to the whitelist, this is not allowed
